export type TeamPlayerStatsType = {
  games: number;
  minutes: number;
  points: number;
  pointsAvg: number;
  fieldGoalsMade: number;
  fieldGoalsMadeAvg: number;
  fieldGoalsAttempted: number;
  fieldGoalsAttemptedAvg: number;
  fieldGoalsPercentage: number;
  threePointersMade: number;
  threePointersMadeAvg: number;
  threePointersAttempted: number;
  threePointersAttemptedAvg: number;
  threePointersPercentage: number;
  freeThrowsMade: number;
  freeThrowsMadeAvg: number;
  freeThrowsAttempted: number;
  freeThrowsAttemptedAvg: number;
  freeThrowsPercentage: number;
  offensiveRebounds: number;
  offensiveReboundsAvg: number;
  defensiveRebounds: number;
  defensiveReboundsAvg: number;
  reboundsTotal: number;
  reboundsTotalAvg: number;
  assists: number;
  assistsAvg: number;
  turnovers: number;
  turnoversAvg: number;
  steals: number;
  stealsAvg: number;
  blocks: number;
  blocksAvg: number;
  foulsPersonal: number;
  foulsPersonalAvg: number;
  plusMinusPointsAvg: number;
};

export type TeamPlayerSeasonRosterType = {
  jerseyNumber: number;
  playingPosition: string;
}

export type TeamPlayerType = {
  providerId: string;
  name: string;
  nickname?: string;
  avatarUrl?: string;
  playingPosition?: string;
  height?: number;
  weight?: number;
  dob?: string;
  nationality?: string;
  shirtNumber?: number;
  stats?: TeamPlayerStatsType;
  seasonRoster?: TeamPlayerSeasonRosterType;
};

export type TeamCompetitionStandingType = {
  position: number;
  positionInGroup: number;
  won: number;
  lost: number;
  drawn: number;
  percentageWon: number;
  homeWins: number;
  homeLosses: number;
  awayWins: number;
  awayLosses: number;
  pointsAverage: number;
  reboundsTotalAverage: number;
  assistsAverage: number;
  fieldGoalsPercentage: number;
  fieldGoalsMadeAverage: number;
  fieldGoalsAttemptedAverage: number;
  threePointersMadeAverage: number;
  threePointersAttemptedAverage: number;
  threePointersPercentage: number;
  freeThrowsMadeAverage: number;
  freeThrowsAttemptedAverage: number;
  freeThrowsPercentage: number;
  offensiveReboundsAverage: number;
  defensiveReboundsAverage: number;
  turnoversAverage: number;
  stealsAverage: number;
  blocksAverage: number;
  foulsPersonalAverage: number;
};

export type TeamSeasonStatsType = {
  points: number;
  pointsAverage: number;
  assists: number;
  assistsAverage: number;
  fieldGoalsMade: number;
  fieldGoalsMadeAverage: number;
  fieldGoalsAttempted: number;
  fieldGoalsAttemptedAverage: number;
  fieldGoalsPercentage: number;
  threePointersMade: number;
  threePointersMadeAverage: number;
  threePointersAttempted: number;
  threePointersAttemptedAverage: number;
  threePointersPercentage: number;
  freeThrowsMade: number;
  freeThrowsMadeAverage: number;
  freeThrowsAttempted: number;
  freeThrowsAttemptedAverage: number;
  freeThrowsPercentage: number;
  offensiveRebounds: number;
  offensiveReboundsAverage: number;
  defensiveRebounds: number;
  defensiveReboundsAverage: number;
  reboundsTotal: number;
  reboundsTotalAverage: number;
  turnovers: number;
  turnoversAverage: number;
  steals: number;
  stealsAverage: number;
  blocks: number;
  blocksAverage: number;
  foulsPersonal: number;
  foulsPersonalAverage: number;
};

export type TeamType = {
  providerId: string;
  name: string;
  nickname?: string;
  code: string;
  city?: string;
  group?: string;
  streamUrl?: string;
  ticketUrl?: string;
  welcomeMessage?: string;
  warCryMessage?: string;
  competitionStandings?: TeamCompetitionStandingType;
  colorPrimary?: string;
  colorSecondary?: string;
  advSmallImageUrl?: string;
  advDefaultImageUrl?: string;
  socialInstagramUrl?: string;
  socialFacebookUrl?: string;
  socialYoutubeUrl?: string;
  socialXUrl?: string;
  socialTiktokUrl?: string;
  socialWebsiteUrl?: string;
  seasonStats?: TeamSeasonStatsType;
};
