import type { Metadata } from 'next';
import {
  Barlow,
  Barlow_Condensed,
  Special_Gothic_Condensed_One,
} from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from './ApolloWrapper';

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const barlowCondensed = Barlow_Condensed({
  variable: '--font-barlow-condensed',
  subsets: ['latin'],
  weight: ['400'],
});

const specialGothicCondensedOne = Special_Gothic_Condensed_One({
  variable: '--font-special-gothic-condensed-one',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'BSN',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${barlowCondensed.variable} ${specialGothicCondensedOne.variable}  antialiased`}
      >
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
