export type PlayerType = {
  providerId: string;
  name: string;
  nickname: string;
  avatarUrl: string;
  playingPosition: string;
  height: number;
  weight: number;
  dob: string;
  nationality: string;
  shirtNumber: number;
  team: {
    code: string;
    name: string;
    nickname: string;
    colorPrimary: string;
  };
  stats?: {
    games: number;
    minutes: number;
    points: number;
    pointsAvg: number;
    fieldGoalsMadeAvg: number;
    fieldGoalsAttemptedAvg: number;
    fieldGoalsPercentage: number;
    threePointersMadeAvg: number;
    threePointersAttemptedAvg: number;
    threePointersPercentage: number;
    freeThrowsMadeAvg: number;
    freeThrowsAttemptedAvg: number;
    freeThrowsPercentage: number;
    offensiveReboundsAvg: number;
    defensiveReboundsAvg: number;
    reboundsTotalAvg: number;
    assistsAvg: number;
    turnoversAvg: number;
    stealsAvg: number;
    blocksAvg: number;
    foulsPersonalAvg: number;
    plusMinusPointsAvg: number;
  };
};
