export const DEFAULT_MEDIA_PROVIDER = 'BSN App • YouTube';

export const MATCH_STATUS = {
  DELAYED: 'DELAYED',
  LOADED: 'LOADED',
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  PERIOD_BREAK: 'PERIOD_BREAK',
  INTERRUPTED: 'INTERRUPTED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED',
  FINISHED: 'FINISHED',
  PROTESTED: 'PROTESTED',
  COMPLETE: 'COMPLETE',
  DRAFT: 'DRAFT',
  BYE: 'BYE',
  SCHEDULED: 'SCHEDULED',
  POSTPONED: 'POSTPONED',
  ABANDONED: 'ABANDONED',
  WARMUP: 'WARMUP',
  PREMATCH: 'PREMATCH',
  ANTHEM: 'ANTHEM',
  ONCOURT: 'ONCOURT',
  STANDBY: 'STANDBY',
  COUNTDOWN: 'COUNTDOWN',
};

export const DATE_ISO_FORMAT = 'YYYY-MM-DD';
export const DATE_TIME_ISO_FORMAT = 'YYYY-MM-DD HH:mm:ss';
export const DATE_TIME_TZ_FORMAT = 'YYYY-MM-DD HH:mm:ss Z';

export const MATCH_DATE_SHORT_FORMAT = 'D MMM';
export const MATCH_DATE_FORMAT = 'ddd, D MMMM';
export const MATCH_DATE_FORMAT_SHORT_MONTH = 'ddd, D MMM';
export const MATCH_TIME_FORMAT = 'h:mm A';

export const PLAYER_BIRTHDAY_FORMAT = 'D/M/YYYY';
